@rootURL = http://localhost:3000
@apiEP = {{rootURL}}/api/v1
@adminEP = {{apiEP}}/admin
@authEP = {{apiEP}}/auth
@userEP = {{apiEP}}/users
@bookEP = {{apiEP}}/books
@borrowEP = {{apiEP}}/borrows
@reviewEP = {{apiEP}}/reviews
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzZGYyQHNkZmMuY29tIiwiaWF0IjoxNzYzMTg5NTYxLCJleHAiOjE3NjMyNzU5NjF9.Z67MoZQ_2RDTdqt8oYVBKQlhUTy0I76199cWuiK-PwQ

###################  Authentication #######################

### Register -public
POST {{authEP}}/register
Content-Type: application/json

{
    "fName": "example",
    "lName": "example",
    "phone": "34567",
    "email": "admin@test.com",
    "password": "admin@test.com"
}

### Login -public
POST {{authEP}}/login
Content-Type: application/json

{
    "email" : "asdf2@sdfc.com",
    "password" : "sdfdsf"
}

### renew jwt -any
GET {{authEP}}/renew-jwt
Authorization: {{authToken}}


######################   USERS   ############################

### Get my details
GET {{authEP}}/users
Authorization: {{authToken}}


### Get all users
GET {{userEP}}
Authorization: {{authToken}}


######################   BOOKS   ############################

### get all active books -public or any
GET {{bookEP}}/public

### Get all books (active and inactives) -admin
GET {{bookEP}}
Authorization: {{authToken}}

### create a book -admin
POST {{bookEP}}
Authorization: {{authToken}}
Content-Type: application/json

{
    "title": "BOOK_TITLE5",
    "author": "AUTHOR",
    "isbn": "ISBN5",
    "publishedYear": 1990,
    "thumbnail": "THUMBNAIL",
    "description": "BOOK_DESCRIPTION"
}

### make book active -admin
PATCH {{bookEP}}/6917f8d9490124ff2fd1bcd1
Authorization: {{authToken}}
Content-Type: application/json

{
    "status" : "active"
}

######################   BORROWS   #########################

### borrow book -any
POST {{borrowEP}}/69151eee2ac6ad0fb3e3e5e6
Authorization: {{authToken}}

### get my borrows -any
GET {{borrowEP}}
Authorization: {{authToken}}

### get all borrows -admin
GET {{borrowEP}}/all
Authorization: {{authToken}}

### return a borrow-update borrow -any
PATCH {{borrowEP}}/return/691822e025b558baf5880f07
Authorization: {{authToken}}

######################   REVIEW   ############################

### Leave a review
POST {{reviewEP}}/691822e025b558baf5880f07
Authorization: {{authToken}}
Content-Type: application/json

{
    "title" : "REVIEW 1",
    "description" : "Description",
    "rating" : 1
}

### approve a review-make review active
PATCH {{reviewEP}}/6918230025b558baf5880f10
Authorization: {{authToken}}
Content-Type: application/json

{
    "status" : "active"
}

### get my reviews (active and inactive?)
GET {{reviewEP}}
Authorization: {{authToken}}

### get all reviews-admin
GET {{reviewEP}}/all
Authorization: {{authToken}}